shared:
  image: centos:centos7

jobs:
  job-1-2:
    requires: ~sd@9298:job-1-1
    steps:
      - echo: echo hoge

  job-1-3:
    requires: job-1-2
    steps:
      - echo: echo hoge

  job-2-2:
    requires: ~sd@9298:job-2-1
    steps:
      - echo: echo hoge
